---
# defaults file for promtail
promtail_apt_update_cache: True
promtail_version: "2.8.4"
promtail_dist_url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-{{ go_arch }}.zip"
promtail_custom_checksum: ""
promtail_config_dir: /etc/promtail
promtail_config_file_sd_dir: "{{ promtail_config_dir }}/file_sd"
promtail_config_file: "{{ promtail_config_dir }}/promtail.yml"
promtail_config_expand_env: "false"

promtail_system_user: promtail
promtail_system_group: "{{ promtail_system_user }}"
promtail_user_additional_groups: "adm"
promtail_systemd_service_template_file: service.j2
promtail_systemd_service: promtail
rsyslog_systemd_service: rsyslog

promtail_binary_local_dir: ""
promtail_binary_propagate: False

promtail_install_dir: /opt/promtail
promtail_tmp_dir: /tmp


promtail_log_level: info
# One of: debug, info, warn, error

promtail_config_server:
  http_listen_port: 9080

promtail_loki_server_dev_url: http://IP:3100
promtail_loki_server_prod_url: http://IP:8080
# promtail_config_clients:
#   - url: "{{ promtail_loki_server_url }}/loki/api/v1/push"

promtail_positions_directory: /opt/promtail
promtail_config_positions:
  filename: "{{ promtail_positions_directory }}/positions.yml"

#promtail_config_scrape_configs: []
promtail_config_scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:20514
      listen_protocol: tcp
      idle_timeout: 600s
      labels:
        job: syslog
        agent: promtail
    relabel_configs:
      - source_labels: [__syslog_message_hostname]
        target_label: ComputerName
      - source_labels: [__syslog_message_severity]
        target_label: EventType
      - source_labels: [__syslog_message_app_name]
        target_label: Channel
      - source_labels: [__syslog_message_facility]
        target_label: facility

promtail_config_include_default_file_sd_config: false

promtail_config_default_file_sd_config:
  - job_name: file_sd
    file_sd_configs:
      - files:
          - "{{ promtail_config_file_sd_dir }}/*.yml"
          - "{{ promtail_config_file_sd_dir }}/*.yaml"
          - "{{ promtail_config_file_sd_dir }}/*.json"

promtail_target_config: {}
#  promtail_target_config:
#    sync_period: "10s"