---
# add proxy to dnf
- name: Check dnf proxy
  lineinfile:
    state: absent
    path: "/etc/dnf/dnf.conf"
    regexp: "^proxy="
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Define couchbase.host if undefined
  lineinfile:
    state: present
    path: "/etc/dnf/dnf.conf"
    line: "proxy={{ zabbix_http_proxy }}"
  when: check.found == 0

- name: (RedHat) Get Gitlab repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/{{ gitlab_runner_package_name }}/script.rpm.sh"
    dest: /tmp/gitlab-runner.script.rpm.sh
    mode: 0744
  environment:
    https_proxy: "{{ zabbix_http_proxy }}"
  when: gitlab_runner_skip_package_repo_install is not defined or not gitlab_runner_skip_package_repo_install

- name: (RedHat) Install Gitlab repository
  command: >
    {% if ansible_distribution == "Rocky" %}
    env os=el dist={{ ansible_distribution_major_version }}
    {% endif %}
    bash /tmp/gitlab-runner.script.rpm.sh
  args:
    creates: "/etc/yum.repos.d/runner_{{ gitlab_runner_package_name }}.repo"
  become: true
  environment:
    https_proxy: "{{ zabbix_http_proxy }}"
  when: gitlab_runner_skip_package_repo_install is not defined or not gitlab_runner_skip_package_repo_install

- name: (RedHat) Update gitlab_runner_package_name
  set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}-{{ gitlab_runner_package_version }}"
    gitlab_runner_package_state: "present"
  when: gitlab_runner_package_version is defined

- name: (RedHat) Set gitlab_runner_package_name
  set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}"
    gitlab_runner_package_state: "latest"
  when: gitlab_runner_package_version is not defined

- name: (RedHat) Install GitLab Runner
  ansible.builtin.dnf:
    name: 
      - "{{ gitlab_runner_package }}"
    state: "{{ gitlab_runner_package_state }}"
    update_cache: true
  notify: restart gitlab-runner