# tasks file for openresty-nginx
- name: Check dnf proxy
  lineinfile:
    state: absent
    path: "/etc/dnf/dnf.conf"
    regexp: "^proxy="
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Define couchbase.host if undefined
  lineinfile:
    state: present
    path: "/etc/dnf/dnf.conf"
    line: "proxy={{ zabbix_http_proxy }}"
  when: check.found == 0

- name: Install OpenResty gpg key
  rpm_key: key={{ openresty_gpg_key_url }}
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"

- name: Enable OpenResty repo
  template:
    src: openresty.repo.rhel.j2
    dest: /etc/yum.repos.d/openresty.repo
    owner: root
    group: root
    mode: 0644

- name: install pkg
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: 
    - "{{ packages }}"
