---
# handlers file for promtail
- name: Restart promtail
  become: True
  systemd:
    name: "{{ promtail_systemd_service }}"
    state: restarted
    daemon_reload: True
- name: Restart rsyslog
  become: True
  systemd:
    name: "{{ rsyslog_systemd_service }}"
    state: restarted
    daemon_reload: True
    