---

- name: (Debian) install "{{ ca_package_name }}"
  apt:
    pkg: "{{ ca_package_name }}"
    state: latest
    update_cache: true
    cache_valid_time: 0
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"

- name: (Debian) Copy cert.
  copy:
    src: '{{ item }}'
    dest: "{{ ubuntu_ca_path }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - name.crt

  notify:
    - update trusted ca debian
