---
# add proxy to dnf
- name: Redhat Check dnf proxy
  lineinfile:
    state: absent
    path: "/etc/dnf/dnf.conf"
    regexp: "^proxy="
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Redhat Define couchbase.host if undefined
  lineinfile:
    state: present
    path: "/etc/dnf/dnf.conf"
    line: "proxy={{ zabbix_http_proxy }}"
  when: check.found == 0

- name: Redhat create certificates directories
  file:
    state: directory
    path: "{{ rocky_ca_path }}"

- name: Redhat install "{{ ca_package_name }}"
  ansible.builtin.dnf:
    name: 
      - "{{ ca_package_name }}"
    state: latest
    update_cache: true

- name: Redhat Copy cert.
  copy:
    src: '{{ item }}'
    dest: "{{ rocky_ca_path }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - name.crt

  notify:
    - update trusted ca redhat