---
# tasks file for drweb-config
  - name: Check that the {{ drweb_config }} exists
    stat:
      path: "{{ drweb_config }}"
    ignore_errors: True
    register: stat_result

  - name: test result
    ansible.builtin.debug:
      msg: DRWEB NOT INSTALLED
    when: stat_result.stat.exists == false

  - name: string found "CPUQuota=50%"
    ansible.builtin.lineinfile:
      name: "{{ drweb_config }}"
      line: "CPUQuota=50%"
      state: present
    check_mode: true
    register: drweb_config_CPUQuota
    # failed_when: (conf is changed) or (conf is failed)
    when: stat_result.stat.exists

  # - name: print home_dirs variable
  #   ansible.builtin.debug:
  #     var: drweb_config_CPUQuota

  - name: Ansible replace string example
    replace:
      path: "{{ drweb_config }}"
      regexp: CPUQuota=\S+
      replace: 'CPUQuota=50%'
    when: stat_result.stat.exists and ( (drweb_config_CPUQuota is changed) or (drweb_config_CPUQuota is failed))
    notify: daemon_reload

  - name: add a new string CPUQuota=50% the match
    ansible.builtin.lineinfile:
      path: "{{ drweb_config }}"
      # regexp: '\[Service]'
      insertafter: '\[Service]'
      line: "CPUQuota=50%"
      firstmatch: yes
      state: present
      backup: yes
    when: stat_result.stat.exists and ((drweb_config_CPUQuota is changed) or (drweb_config_CPUQuota is failed))
    notify: daemon_reload