---
- name: Creates rabbitmq_users_list fact
  set_fact:
    rabbitmq_users_list: {}

- name: Ensure that rabbitmq guest user is removed
  rabbitmq_user:
    user: guest
    state: absent
  no_log: true

- name: Combine rabbitmq_users_default with rabbitmq_users
  set_fact:
    rabbitmq_users_list: "{{ rabbitmq_users_default | default({}, true) | combine(rabbitmq_users | default({}, true), recursive=True) }}"

- name: Show users to be processed
  debug:
    msg: "{{ rabbitmq_users_list }}"
    verbosity: 2

- name: Create RabbitMQ users
  rabbitmq_user:
    user: "{{ item.key }}"
    password: "{{ item.value.password }}"
    vhost: "{{ item.value.vhost | default (omit) }}"
    configure_priv: "{{ item.value.configure_priv | default('.*') }}"
    read_priv: "{{ item.value.read_priv | default('.*') }}"
    write_priv: "{{ item.value.write_priv | default('.*') }}"
    tags: "{{ item.value.tags | default(omit) }}"
    state: "{{ item.value.state | default('present') }}"
    update_password: "{{ item.value.update_password | default('always') }}"
  no_log: true
  ignore_errors: True
  with_dict: "{{ rabbitmq_users_list }}"