- blockinfile:
    path: /etc/hosts
    block: "{{ rabbitmq_hosts }}"
    owner: root
    group: root
    mode: 0644

- name: Set hostname from inventory
  hostname:
    name: "{{ inventory_hostname }}"