---
# handlers file for zabbix-agent

- name: restart zabbix-agent
  service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
    enabled: true
  become: true
  when:
    - not zabbix_agent_docker
    - ansible_os_family != "Windows" and ansible_os_family != "Darwin"

- name: "clean repo files from proxy creds"
  shell: ls /etc/yum.repos.d/zabbix* && sed -i 's/^proxy =.*//' /etc/yum.repos.d/zabbix* || true
  become: true

  